server:
  port: 8765

spring:
  application:
    name: provider

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    thymeleaf:
      cache: false
      mode: LEGACYHTML5



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
